#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=mN_jYKCTEwU&t=10s;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
