#!/usr/bin/env bash
# redirect to 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/ {\n\t\ttry_files $uri $uri\/ =404;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
