#!/usr/bin/env bash
# configures Nginx to run and listen on port 80 in an Ubuntu container
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
