#!/usr/bin/env bash
#  Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

num=1
while [ $num -le 20 ]
do
echo "$num"
    case $num in
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;;
    esac
((num++))
done
