#!/usr/bin/env bash
# Bash script that gives you information about the school file

if [[ -f school ]]; then
    echo "school file exists"
    if [[ ! -s school ]]; then
        echo "school file is empty"
        else
        echo "school file is not empty"
    fi
    if [[ -f school ]]; then
        echo "school is a regular file"
    fi
    echo "school file does not exist"
fi
