#!/usr/bin/env bash
# Run nginx as nginx user
sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx start -u nginx
